//==============================================================================
// Academy engine — brand profile type (Academy Forge)
//==============================================================================
// The engine is brand-agnostic. Everything a brand changes — names, ranks,
// certificate wording, cookie, commerce, narration — comes from ONE object:
// `content/academy.config.ts`, generated by `install.sh <brand>` from
// `~/dev/academy-forge/brands/<brand>/academy.json`. Never edit the generated
// file by hand; edit the profile and re-run install.
//
// Colours are NOT in here: they are CSS variables in styles/academy.css
// (also generated), consumed through the `academy-*` Tailwind tokens.
//==============================================================================

export interface RankLevel {
  name: string;
  /** XP needed to reach this rank. `null` = the top rank, awarded by certification only. */
  minXp: number | null;
  /** Swatch colour (hex). */
  color: string;
}

export interface AcademyConfig {
  /** Profile slug: bl · pmma · tsai · gift-connect */
  slug: string;
  site: {
    /** Canonical site origin, no trailing slash. Fallback for checkout redirects. */
    url: string;
    /** Source folder relative to the repo root: "src" or "" (app/ at root). */
    srcDir: string;
  };
  academy: {
    /** Full display name, e.g. "Master's Edge Academy". */
    name: string;
    /** Trailing part of `name` rendered in the accent colour (must be a suffix of `name`). */
    nameAccent: string;
    /** Brand / organisation line for <title>, e.g. "Brett Lechtenberg". */
    kicker: string;
    /** Meta description of the academy shell. */
    description: string;
    /** Emoji used as the academy mark in nav + login. */
    icon: string;
    /** Owner's first name for "Only Brett posts here", "Brett's feedback". */
    ownerFirstName: string;
    /** Avatar picker choices; the first is the signup default. */
    avatars: string[];
    copy: {
      loginWelcome: string;
      signupWelcome: string;
      loginCta: string;
      signupCta: string;
      dashboardMotto: string;
      continueCta: string;
      backCta: string;
      membersBlurb: string;
      sidebarBlurb: string;
    };
  };
  ranks: {
    system: "belts" | "levels" | "milestones";
    /** Ordered low → high. The last entry is the top rank (minXp null). */
    levels: RankLevel[];
    /** Suffix stripped for compact labels (leaderboard chips), e.g. " Belt". */
    shortSuffix: string;
    top: {
      /** Page title lead, e.g. "Black Belt" (rendered before "Certification"). */
      title: string;
      /** me_awards.badge_slug for the top credential. Stable — never rename after launch. */
      badgeSlug: string;
      badgeName: string;
      badgeEmoji: string;
      badgeDescription: string;
      /** "Certified Master's Edge — Black Belt" */
      certifiedHeading: string;
      /** Dashboard line once certified. */
      certifiedLine: string;
      /** Name of the credential in prose: "the Certified Master's Edge credential". */
      credentialPhrase: string;
      /** Locked-page hint: "…to unlock your Black Belt test." */
      unlockHint: string;
      /** Capstone brief shown on the certification page. */
      projectBrief: string;
    };
    /** Issue a Certifier credential for the top badge (needs CERTIFIER_* env). */
    certifierEnabled: boolean;
  };
  certificate: {
    signer: string;
    signerTitle: string;
    /** Certificate body for the top tier (before the rank line). */
    topBody: string;
    /** Rank line on the top certificate, e.g. "⬛ BLACK BELT — CERTIFIED MASTER'S EDGE". */
    topLine: string;
    sealEmoji: string;
  };
  commerce: {
    stripe: boolean;
    stripeProductPrefix: string;
  };
  narration: {
    voice: string;
    /** "Narrated by Brett" */
    narrator: string;
  };
  session: {
    /** HTTP-only cookie name. Unique per brand so two academies on one browser never collide. */
    cookie: string;
  };
}

/** Split `name` into [lead, accent] using `nameAccent` as the suffix. */
export function splitAcademyName(cfg: AcademyConfig): [string, string] {
  const { name, nameAccent } = cfg.academy;
  if (nameAccent && name.endsWith(nameAccent)) {
    return [name.slice(0, name.length - nameAccent.length).trimEnd(), nameAccent];
  }
  return [name, ""];
}
