//==============================================================================
// Academy — brand profile (GENERATED by the Academy Forge — do not edit)
//==============================================================================
// Source: ~/dev/academy-forge/brands/bl/academy.json
// Regenerate: bash ~/dev/academy-forge/install.sh bl
// Colours live in styles/academy.css (same generator).
//==============================================================================

import type { AcademyConfig } from "@/lib/academy-config";

export const academyConfig: AcademyConfig = {
  "slug": "bl",
  "site": {
    "url": "https://www.brettlechtenberg.com",
    "srcDir": "src",
    "deploy": "cli",
    "gitBranch": "main"
  },
  "academy": {
    "name": "Master's Edge Academy",
    "nameAccent": "Academy",
    "kicker": "Brett Lechtenberg",
    "description": "Private learning academy for Master's Edge members.",
    "icon": "🥋",
    "ownerFirstName": "Brett",
    "avatars": [
      "🥋",
      "🦅",
      "🐯",
      "🐉",
      "🦁",
      "⚡",
      "🔥",
      "🏔️",
      "🌟",
      "🥷",
      "🛡️",
      "⚔️"
    ],
    "copy": {
      "loginWelcome": "Welcome back. Step onto the mat.",
      "signupWelcome": "Free to join. Unlock courses with a purchase or your gift code.",
      "loginCta": "Enter the Academy",
      "signupCta": "Begin Training",
      "dashboardMotto": "Keep training. Mastery is a practice.",
      "continueCta": "Continue Training",
      "backCta": "Back to Training",
      "membersBlurb": "The people training alongside you. Add your tagline on your profile.",
      "sidebarBlurb": "Private group. We don't just talk about mastery — we train it, measure it, and prove it."
    }
  },
  "ranks": {
    "system": "belts",
    "shortSuffix": " Belt",
    "levels": [
      {
        "name": "White Belt",
        "minXp": 0,
        "color": "#F5F5F5"
      },
      {
        "name": "Yellow Belt",
        "minXp": 100,
        "color": "#FACC15"
      },
      {
        "name": "Orange Belt",
        "minXp": 250,
        "color": "#FB923C"
      },
      {
        "name": "Green Belt",
        "minXp": 450,
        "color": "#22C55E"
      },
      {
        "name": "Blue Belt",
        "minXp": 700,
        "color": "#3B82F6"
      },
      {
        "name": "Purple Belt",
        "minXp": 1000,
        "color": "#A855F7"
      },
      {
        "name": "Brown Belt",
        "minXp": 1400,
        "color": "#92400E"
      },
      {
        "name": "Red Belt",
        "minXp": 1900,
        "color": "#DC2626"
      },
      {
        "name": "Black Belt",
        "minXp": null,
        "color": "#1A1A1A"
      }
    ],
    "top": {
      "title": "Black Belt",
      "badgeSlug": "certified-masters-edge",
      "badgeName": "Certified Master's Edge",
      "badgeEmoji": "🏆",
      "badgeDescription": "Completed the full certification",
      "certifiedHeading": "Certified Master's Edge — Black Belt",
      "certifiedLine": "You are a Certified Master's Edge Black Belt 🏆",
      "credentialPhrase": "the Certified Master's Edge credential",
      "unlockHint": "Pass every training module to unlock your Black Belt test.",
      "projectBrief": "Apply all three tools to your own business: fire yourself from one role, design and run your ideal week for two weeks, and journal one significant decision. Describe what you did, what changed, and what you measured. Link supporting material if you have it."
    },
    "certifierEnabled": true
  },
  "certificate": {
    "signer": "Brett Lechtenberg",
    "signerTitle": "Founder, Master's Edge · 8th-Degree Black Belt",
    "topBody": "has completed all training modules, submitted an approved capstone project, and passed the final examination of the Master's Edge Business Program — earning the rank of",
    "topLine": "⬛ BLACK BELT — CERTIFIED MASTER'S EDGE",
    "sealEmoji": "🥋"
  },
  "commerce": {
    "stripe": true,
    "stripeProductPrefix": "Master's Edge Academy — "
  },
  "narration": {
    "voice": "am_michael",
    "narrator": "Brett"
  },
  "session": {
    "cookie": "bl_academy_session"
  },
  "supabase": {
    "project": "yrfsquzzbgnmkfbuapfk"
  },
  "email": {
    "from": "Master's Edge Academy <academy@auth.brettlechtenberg.com>",
    "replyTo": "brett@brettlechtenberg.com"
  },
  "vocab": {
    "module": "module",
    "modules": "modules",
    "course": "course",
    "courses": "courses"
  },
  "signup": {
    "accessCodeEnv": null,
    "accessCodeLabel": "Program code",
    "accessCodePlaceholder": "Enter your program code",
    "accessCodeMismatch": "That code doesn't match. Check with your program contact."
  }
};
